service: marketing-interview-backend

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  novenueBucketName: 'marketing-interview-backend-${self:provider.stage}'
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: 'yarn'
    excludeFiles: src/**/*.test.[t|j]s
  local:
    frontend_url: 'http://localhost:8000'
  dev:
    frontend_url: 'https://dev.activekids.cmdtests.com'
  prod:
    frontend_url: 'https://activekids.sainsburys.co.uk'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, "local"}
  region: eu-west-1
  environment:
    STAGE: ${self:provider.stage}

functions:
  movieSearch:
    handler: src/index.default
    events:
      - http:
          path: /media_search
          method: get
          cors: true
